theme: merlot
#remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
  #theme: jekyll-theme-minimal
title: Voyage of EWC
description: Some call me Will. Strangers call me zanenab.  <h2>{{ site.data.samplelist.docs_list_title }}</h2><ul>{% for item in site.data.samplelist.docs %}<li><a href="{{ item.url }}">{{ item.title }}</a></li>{% endfor %}</ul>
